Repository bank-vaults/secret-init, pull requests merged in 2024-02, with the labels that each got.

#51 feat: Add e2e tests
  .github/workflows/ci.yaml
  Makefile
  docker-compose.yaml
  e2e/file-provider.bats
  e2e/vault-provider.bats
  flake.nix
  provider/vault/vault_test.go
Labels: enhancement, size/M

#77 feat: Cancel previous workflow on push
  .github/workflows/ci.yaml
Labels: size/XS, kind/enhancement

#73 chore: update bank-vaults deps
  .licensei.toml
  go.mod
  go.sum
Labels: size/XL

#75 fix: handle different vault injection cases
  common/config.go
  e2e/multi-provider.bats
  e2e/vault-provider.bats
  env_store.go
  env_store_test.go
  provider/file/config_test.go
  provider/vault/config_test.go
Labels: size/M

#81 feat: Add usage examples
  README.md
  examples/README.md
  examples/secret-init-as-a-standalone-tool.md
Labels: kind/enhancement, size/M, kind/documentation, kind/feature

#83 fix: fix link by adding new directory
  examples/README.md
  examples/standalone-tool.md
Labels: size/XS, kind/documentation

#85 refactor: move provider, and common to pkg package
  README.md
  env_store.go
  env_store_test.go
  main.go
  pkg/common/config.go
  pkg/common/config_test.go
  pkg/provider/file/config.go
  pkg/provider/file/config_test.go
  pkg/provider/file/file.go
  pkg/provider/file/file_test.go
  pkg/provider/provider.go
  pkg/provider/vault/client_logger.go
  pkg/provider/vault/config.go
  pkg/provider/vault/config_test.go
  pkg/provider/vault/daemon_secret_renewer.go
  pkg/provider/vault/vault.go
  pkg/provider/vault/vault_test.go
Labels: size/S

#87 fix: add VAULT_LOG_LEVEL env to sanitize so it can be set
  pkg/provider/vault/config.go
Labels: size/S, kind/bug
