Repository bank-vaults/secret-init, pull requests merged in 2024-06, with the labels that each got.

#154 feat: add issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: kind/enhancement, size/M

#158 chore: bump go version and bv packages
  go.mod
  go.sum
  pkg/provider/bao/bao.go
  pkg/provider/vault/vault.go
Labels: size/XL

#179 chore: add change from vault-env to fix log level configurability
  main.go
Labels: size/XS
